# Generated by Django 4.2.16 on 2024-09-05 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='uploads/movies')),
                ('coverimage', models.ImageField(default='', upload_to='uploads/coverimages')),
                ('description', models.CharField(max_length=500)),
                ('directors', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=50)),
                ('actors', models.CharField(max_length=200)),
                ('crew', models.CharField(default='', max_length=200)),
                ('movie_format', models.CharField(default='', max_length=30)),
                ('duration', models.CharField(default='', max_length=20)),
                ('language', models.CharField(default='', max_length=30)),
                ('cerificate', models.CharField(default='', max_length=20)),
                ('release_date', models.DateField(default=datetime.date(2024, 9, 5))),
            ],
        ),
    ]
